<a href="https://colab.research.google.com/github/Mercymerine/Machine_learning2/blob/main/RNA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Importing Packages**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.preprocessing import MinMaxScaler
from scipy.cluster import hierarchy
from scipy.spatial import distance_matrix
from matplotlib import pyplot as plt
from sklearn import manifold, datasets
from sklearn.cluster import AgglomerativeClustering

In [3]:
rna = pd.read_csv('/content/codon_usage.csv', low_memory=False)
rna.head()

Kingdom  DNAtype  SpeciesID  Ncodons  \
0     vrl        0     100217     1995   
1     vrl        0     100220     1474   
2     vrl        0     100755     4862   
3     vrl        0     100880     1915   
4     vrl        0     100887    22831   

                               SpeciesName      UUU      UUC      UUA  \
0  Epizootic haematopoietic necrosis virus  0.01654  0.01203  0.00050   
1                         Bohle iridovirus  0.02714  0.01357  0.00068   
2             Sweet potato leaf curl virus  0.01974   0.0218  0.01357   
3             Northern cereal mosaic virus  0.01775  0.02245  0.01619   
4           Soil-borne cereal mosaic virus  0.02816  0.01371  0.00767   

       UUG      CUU  ...      CGG      AGA      AGG      GAU      GAC  \
0  0.00351  0.01203  ...  0.00451  0.01303  0.03559  0.01003  0.04612   
1  0.00678  0.00407  ...  0.00136  0.01696  0.03596  0.01221  0.04545   
2  0.01543  0.00782  ...  0.00596  0.01974  0.02489  0.03126  0.02036   
3  0.00992  0.01567  ...  0.00366  0.01410  0.01671  0.03760  0.01932   
4  0.03679  0.01380  ...  0.00604  0.01494  0.01734  0.04148  0.02483   

       GAA      GAG      UAA      UAG      UGA  
0  0.01203  0.04361  0.00251  0.00050  0.00000  
1  0.01560  0.04410  0.00271  0.00068  0.00000  
2  0.02242  0.02468  0.00391  0.00000  0.00144  
3  0.03029  0.03446  0.00261  0.00157  0.00000  
4  0.03359  0.03679  0.00000  0.00044  0.00131  

[5 rows x 69 columns]

In [4]:
rna.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13028 entries, 0 to 13027
Data columns (total 69 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Kingdom      13028 non-null  object 
 1   DNAtype      13028 non-null  int64  
 2   SpeciesID    13028 non-null  int64  
 3   Ncodons      13028 non-null  int64  
 4   SpeciesName  13028 non-null  object 
 5   UUU          13028 non-null  object 
 6   UUC          13028 non-null  object 
 7   UUA          13028 non-null  float64
 8   UUG          13028 non-null  float64
 9   CUU          13028 non-null  float64
 10  CUC          13028 non-null  float64
 11  CUA          13028 non-null  float64
 12  CUG          13028 non-null  float64
 13  AUU          13028 non-null  float64
 14  AUC          13028 non-null  float64
 15  AUA          13028 non-null  float64
 16  AUG          13028 non-null  float64
 17  GUU          13028 non-null  float64
 18  GUC          13028 non-null  float64
 19  GUA 

In [5]:
rna.iloc[:, :6].isnull().sum()

Kingdom        0
DNAtype        0
SpeciesID      0
Ncodons        0
SpeciesName    0
UUU            0
dtype: int64

In [6]:
rna.iloc[:, :6].nunique()

Kingdom           11
DNAtype           11
SpeciesID      12368
Ncodons         7103
SpeciesName    13016
UUU             4791
dtype: int64

In [7]:
rna.nunique()

Kingdom           11
DNAtype           11
SpeciesID      12368
Ncodons         7103
SpeciesName    13016
               ...  
GAA             4827
GAG             4686
UAA              703
UAG              422
UGA             1786
Length: 69, dtype: int64

In [8]:
rna.describe()

DNAtype      SpeciesID       Ncodons           UUA           UUG  \
count  13028.000000   13028.000000  1.302800e+04  13028.000000  13028.000000   
mean       0.367209  130451.105926  7.960576e+04      0.020637      0.014104   
std        0.688726  124787.086107  7.197010e+05      0.020709      0.009280   
min        0.000000       7.000000  1.000000e+03      0.000000      0.000000   
25%        0.000000   28850.750000  1.602000e+03      0.005610      0.007108   
50%        0.000000   81971.500000  2.927500e+03      0.015260      0.013360   
75%        1.000000  222891.250000  9.120000e+03      0.029485      0.019810   
max       12.000000  465364.000000  4.066258e+07      0.151330      0.101190   

                CUU           CUC           CUA           CUG           AUU  \
count  13028.000000  13028.000000  13028.000000  13028.000000  13028.000000   
mean       0.017820      0.018288      0.019044      0.018450      0.028352   
std        0.010586      0.014572      0.024250      0.016578      0.017507   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.010890      0.007830      0.005307      0.007180      0.016360   
50%        0.016130      0.014560      0.009685      0.012800      0.025475   
75%        0.022730      0.025112      0.017245      0.024315      0.038113   
max        0.089780      0.100350      0.163920      0.107370      0.154060   

       ...           CGG           AGA           AGG           GAU  \
count  ...  13028.000000  13028.000000  13028.000000  13028.000000   
mean   ...      0.005454      0.009929      0.006422      0.024178   
std    ...      0.006605      0.008574      0.006387      0.013828   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.001220      0.001690      0.001170      0.012380   
50%    ...      0.003530      0.009270      0.004545      0.025420   
75%    ...      0.007150      0.015922      0.010250      0.034190   
max    ...      0.055540      0.098830      0.058430      0.185660   

                GAC           GAA           GAG           UAA           UAG  \
count  13028.000000  13028.000000  13028.000000  13028.000000  13028.000000   
mean       0.021164      0.028290      0.021683      0.001645      0.000592   
std        0.013041      0.014342      0.015018      0.001834      0.000907   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.011860      0.017360      0.009710      0.000560      0.000000   
50%        0.019070      0.026085      0.020540      0.001380      0.000420   
75%        0.027690      0.036800      0.031122      0.002370      0.000830   
max        0.113840      0.144890      0.158550      0.045200      0.025610   

                UGA  
count  13028.000000  
mean       0.006178  
std        0.010344  
min        0.000000  
25%        0.000410  
50%        0.001130  
75%        0.002890  
max        0.106700  

[8 rows x 65 columns]

## **Data Cleaning**

In [9]:
rna.columns

Index(['Kingdom', 'DNAtype', 'SpeciesID', 'Ncodons', 'SpeciesName', 'UUU',
       'UUC', 'UUA', 'UUG', 'CUU', 'CUC', 'CUA', 'CUG', 'AUU', 'AUC', 'AUA',
       'AUG', 'GUU', 'GUC', 'GUA', 'GUG', 'GCU', 'GCC', 'GCA', 'GCG', 'CCU',
       'CCC', 'CCA', 'CCG', 'UGG', 'GGU', 'GGC', 'GGA', 'GGG', 'UCU', 'UCC',
       'UCA', 'UCG', 'AGU', 'AGC', 'ACU', 'ACC', 'ACA', 'ACG', 'UAU', 'UAC',
       'CAA', 'CAG', 'AAU', 'AAC', 'UGU', 'UGC', 'CAU', 'CAC', 'AAA', 'AAG',
       'CGU', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG', 'GAU', 'GAC', 'GAA', 'GAG',
       'UAA', 'UAG', 'UGA'],
      dtype='object')

In [10]:
#Dropping the SpeciesID and SpeciesName column
rna.drop(['SpeciesID'], inplace=True, axis=1)

In [11]:
rna.columns

Index(['Kingdom', 'DNAtype', 'Ncodons', 'SpeciesName', 'UUU', 'UUC', 'UUA',
       'UUG', 'CUU', 'CUC', 'CUA', 'CUG', 'AUU', 'AUC', 'AUA', 'AUG', 'GUU',
       'GUC', 'GUA', 'GUG', 'GCU', 'GCC', 'GCA', 'GCG', 'CCU', 'CCC', 'CCA',
       'CCG', 'UGG', 'GGU', 'GGC', 'GGA', 'GGG', 'UCU', 'UCC', 'UCA', 'UCG',
       'AGU', 'AGC', 'ACU', 'ACC', 'ACA', 'ACG', 'UAU', 'UAC', 'CAA', 'CAG',
       'AAU', 'AAC', 'UGU', 'UGC', 'CAU', 'CAC', 'AAA', 'AAG', 'CGU', 'CGC',
       'CGA', 'CGG', 'AGA', 'AGG', 'GAU', 'GAC', 'GAA', 'GAG', 'UAA', 'UAG',
       'UGA'],
      dtype='object')

In [12]:
rna.head()

Kingdom  DNAtype  Ncodons                              SpeciesName      UUU  \
0     vrl        0     1995  Epizootic haematopoietic necrosis virus  0.01654   
1     vrl        0     1474                         Bohle iridovirus  0.02714   
2     vrl        0     4862             Sweet potato leaf curl virus  0.01974   
3     vrl        0     1915             Northern cereal mosaic virus  0.01775   
4     vrl        0    22831           Soil-borne cereal mosaic virus  0.02816   

       UUC      UUA      UUG      CUU      CUC  ...      CGG      AGA  \
0  0.01203  0.00050  0.00351  0.01203  0.03208  ...  0.00451  0.01303   
1  0.01357  0.00068  0.00678  0.00407  0.02849  ...  0.00136  0.01696   
2   0.0218  0.01357  0.01543  0.00782  0.01111  ...  0.00596  0.01974   
3  0.02245  0.01619  0.00992  0.01567  0.01358  ...  0.00366  0.01410   
4  0.01371  0.00767  0.03679  0.01380  0.00548  ...  0.00604  0.01494   

       AGG      GAU      GAC      GAA      GAG      UAA      UAG      UGA  
0  0.03559  0.01003  0.04612  0.01203  0.04361  0.00251  0.00050  0.00000  
1  0.03596  0.01221  0.04545  0.01560  0.04410  0.00271  0.00068  0.00000  
2  0.02489  0.03126  0.02036  0.02242  0.02468  0.00391  0.00000  0.00144  
3  0.01671  0.03760  0.01932  0.03029  0.03446  0.00261  0.00157  0.00000  
4  0.01734  0.04148  0.02483  0.03359  0.03679  0.00000  0.00044  0.00131  

[5 rows x 68 columns]

In [13]:
# Converting the UUU and UUC columns into floats
rna['UUU'] = pd.to_numeric(rna['UUU'], errors='coerce')


In [14]:
rna['UUU'].dtypes

dtype('float64')

In [15]:
rna['UUU'].isnull().sum()

2

In [16]:
rna['UUC'].replace('-', np.nan, inplace=True)

In [17]:
rna['UUC'] = rna['UUC'].astype(float)

In [18]:
rna['UUC'].dtypes

dtype('float64')

In [19]:
rna['UUC'].isnull().sum()

1

In [20]:
rna.head()

Kingdom  DNAtype  Ncodons                              SpeciesName      UUU  \
0     vrl        0     1995  Epizootic haematopoietic necrosis virus  0.01654   
1     vrl        0     1474                         Bohle iridovirus  0.02714   
2     vrl        0     4862             Sweet potato leaf curl virus  0.01974   
3     vrl        0     1915             Northern cereal mosaic virus  0.01775   
4     vrl        0    22831           Soil-borne cereal mosaic virus  0.02816   

       UUC      UUA      UUG      CUU      CUC  ...      CGG      AGA  \
0  0.01203  0.00050  0.00351  0.01203  0.03208  ...  0.00451  0.01303   
1  0.01357  0.00068  0.00678  0.00407  0.02849  ...  0.00136  0.01696   
2  0.02180  0.01357  0.01543  0.00782  0.01111  ...  0.00596  0.01974   
3  0.02245  0.01619  0.00992  0.01567  0.01358  ...  0.00366  0.01410   
4  0.01371  0.00767  0.03679  0.01380  0.00548  ...  0.00604  0.01494   

       AGG      GAU      GAC      GAA      GAG      UAA      UAG      UGA  
0  0.03559  0.01003  0.04612  0.01203  0.04361  0.00251  0.00050  0.00000  
1  0.03596  0.01221  0.04545  0.01560  0.04410  0.00271  0.00068  0.00000  
2  0.02489  0.03126  0.02036  0.02242  0.02468  0.00391  0.00000  0.00144  
3  0.01671  0.03760  0.01932  0.03029  0.03446  0.00261  0.00157  0.00000  
4  0.01734  0.04148  0.02483  0.03359  0.03679  0.00000  0.00044  0.00131  

[5 rows x 68 columns]

In [21]:
rna.shape

(13028, 68)

In [22]:
rna = rna.dropna()
rna = rna.reset_index(drop=True)

In [23]:
rna.head()

Kingdom  DNAtype  Ncodons                              SpeciesName      UUU  \
0     vrl        0     1995  Epizootic haematopoietic necrosis virus  0.01654   
1     vrl        0     1474                         Bohle iridovirus  0.02714   
2     vrl        0     4862             Sweet potato leaf curl virus  0.01974   
3     vrl        0     1915             Northern cereal mosaic virus  0.01775   
4     vrl        0    22831           Soil-borne cereal mosaic virus  0.02816   

       UUC      UUA      UUG      CUU      CUC  ...      CGG      AGA  \
0  0.01203  0.00050  0.00351  0.01203  0.03208  ...  0.00451  0.01303   
1  0.01357  0.00068  0.00678  0.00407  0.02849  ...  0.00136  0.01696   
2  0.02180  0.01357  0.01543  0.00782  0.01111  ...  0.00596  0.01974   
3  0.02245  0.01619  0.00992  0.01567  0.01358  ...  0.00366  0.01410   
4  0.01371  0.00767  0.03679  0.01380  0.00548  ...  0.00604  0.01494   

       AGG      GAU      GAC      GAA      GAG      UAA      UAG      UGA  
0  0.03559  0.01003  0.04612  0.01203  0.04361  0.00251  0.00050  0.00000  
1  0.03596  0.01221  0.04545  0.01560  0.04410  0.00271  0.00068  0.00000  
2  0.02489  0.03126  0.02036  0.02242  0.02468  0.00391  0.00000  0.00144  
3  0.01671  0.03760  0.01932  0.03029  0.03446  0.00261  0.00157  0.00000  
4  0.01734  0.04148  0.02483  0.03359  0.03679  0.00000  0.00044  0.00131  

[5 rows x 68 columns]

## **Feature Transformation**

In [24]:
rna.columns

Index(['Kingdom', 'DNAtype', 'Ncodons', 'SpeciesName', 'UUU', 'UUC', 'UUA',
       'UUG', 'CUU', 'CUC', 'CUA', 'CUG', 'AUU', 'AUC', 'AUA', 'AUG', 'GUU',
       'GUC', 'GUA', 'GUG', 'GCU', 'GCC', 'GCA', 'GCG', 'CCU', 'CCC', 'CCA',
       'CCG', 'UGG', 'GGU', 'GGC', 'GGA', 'GGG', 'UCU', 'UCC', 'UCA', 'UCG',
       'AGU', 'AGC', 'ACU', 'ACC', 'ACA', 'ACG', 'UAU', 'UAC', 'CAA', 'CAG',
       'AAU', 'AAC', 'UGU', 'UGC', 'CAU', 'CAC', 'AAA', 'AAG', 'CGU', 'CGC',
       'CGA', 'CGG', 'AGA', 'AGG', 'GAU', 'GAC', 'GAA', 'GAG', 'UAA', 'UAG',
       'UGA'],
      dtype='object')

In [25]:
rna_feature = rna[['DNAtype', 'Ncodons',  'UUU', 'UUC', 'UUA',
       'UUG', 'CUU', 'CUC', 'CUA', 'CUG', 'AUU', 'AUC', 'AUA', 'AUG', 'GUU',
       'GUC', 'GUA', 'GUG', 'GCU', 'GCC', 'GCA', 'GCG', 'CCU', 'CCC', 'CCA',
       'CCG', 'UGG', 'GGU', 'GGC', 'GGA', 'GGG', 'UCU', 'UCC', 'UCA', 'UCG',
       'AGU', 'AGC', 'ACU', 'ACC', 'ACA', 'ACG', 'UAU', 'UAC', 'CAA', 'CAG',
       'AAU', 'AAC', 'UGU', 'UGC', 'CAU', 'CAC', 'AAA', 'AAG', 'CGU', 'CGC',
       'CGA', 'CGG', 'AGA', 'AGG', 'GAU', 'GAC', 'GAA', 'GAG', 'UAA', 'UAG',
       'UGA' ]]

rna_feature.head()


DNAtype  Ncodons      UUU      UUC      UUA      UUG      CUU      CUC  \
0        0     1995  0.01654  0.01203  0.00050  0.00351  0.01203  0.03208   
1        0     1474  0.02714  0.01357  0.00068  0.00678  0.00407  0.02849   
2        0     4862  0.01974  0.02180  0.01357  0.01543  0.00782  0.01111   
3        0     1915  0.01775  0.02245  0.01619  0.00992  0.01567  0.01358   
4        0    22831  0.02816  0.01371  0.00767  0.03679  0.01380  0.00548   

       CUA      CUG  ...      CGG      AGA      AGG      GAU      GAC  \
0  0.00100  0.04010  ...  0.00451  0.01303  0.03559  0.01003  0.04612   
1  0.00204  0.04410  ...  0.00136  0.01696  0.03596  0.01221  0.04545   
2  0.01028  0.01193  ...  0.00596  0.01974  0.02489  0.03126  0.02036   
3  0.00940  0.01723  ...  0.00366  0.01410  0.01671  0.03760  0.01932   
4  0.00473  0.02076  ...  0.00604  0.01494  0.01734  0.04148  0.02483   

       GAA      GAG      UAA      UAG      UGA  
0  0.01203  0.04361  0.00251  0.00050  0.00000  
1  0.01560  0.04410  0.00271  0.00068  0.00000  
2  0.02242  0.02468  0.00391  0.00000  0.00144  
3  0.03029  0.03446  0.00261  0.00157  0.00000  
4  0.03359  0.03679  0.00000  0.00044  0.00131  

[5 rows x 66 columns]

Min-Max Scaler is suitable for:
Algorithms sensitive to scale, such as neural networks and distance-based algorithms (K-Nearest Neighbors).
Sparse data, as it preserves sparsity.
Models where features have different units or ranges, to ensure equal contribution to the model.
Min-Max Scaler’s transformation is based on the minimum and maximum values of each feature, scaling them to a common range (typically [0, 1]).
Unlike StandardScaler, Min-Max Scaler does not assume a specific distribution and is more robust to outliers.
Min-Max Scaler can be used as a preprocessing step before training a machine learning model, such as logistic regression.

In [26]:
# Using min max scaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
rna_feature_scaled = scaler.fit_transform(rna_feature)
print(rna_feature_scaled)

[[0.00000000e+00 2.44702727e-05 7.61159687e-02 ... 5.55309735e-02
  1.95236236e-02 0.00000000e+00]
 [0.00000000e+00 1.16571952e-05 1.24896457e-01 ... 5.99557522e-02
  2.65521281e-02 0.00000000e+00]
 [0.00000000e+00 9.49790886e-05 9.08421537e-02 ... 8.65044248e-02
  0.00000000e+00 1.34957826e-02]
 ...
 [8.33333333e-02 1.68709619e-05 6.54855039e-02 ... 7.87610619e-02
  4.64662241e-02 1.89034677e-01]
 [0.00000000e+00 1.00000000e+00 8.08559595e-02 ... 2.19026549e-02
  3.08473253e-02 1.46204311e-02]
 [8.33333333e-02 2.21289914e-01 8.18223654e-02 ... 3.45132743e-02
  4.45138618e-02 2.02530459e-01]]


In [27]:
dist_matrix = distance_matrix(rna_feature_scaled, rna_feature_scaled)
print(dist_matrix)

[[0.         0.38928545 0.94493444 ... 1.47515749 1.22700362 1.3351641 ]
 [0.38928545 0.         0.94437158 ... 1.44787355 1.24610339 1.31150987]
 [0.94493444 0.94437158 0.         ... 1.40452914 1.17116139 1.20578005]
 ...
 [1.47515749 1.44787355 1.40452914 ... 0.         1.6178877  0.51408096]
 [1.22700362 1.24610339 1.17116139 ... 1.6178877  0.         1.32194152]
 [1.3351641  1.31150987 1.20578005 ... 0.51408096 1.32194152 0.        ]]


In [28]:
agglom = AgglomerativeClustering(n_clusters = 11, linkage = 'average')
agglom.fit(dist_matrix)
agglom.labels_

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_agglomerative.py:567: ClusterWarning: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  out = hierarchy.linkage(X, method=linkage, metric=affinity)


array([9, 9, 0, ..., 2, 5, 2])

In [29]:
# Add it to our data frame to indicate which cluster a row belongs to
rna['Cluster_'] = agglom.labels_
rna.head()

Kingdom  DNAtype  Ncodons                              SpeciesName      UUU  \
0     vrl        0     1995  Epizootic haematopoietic necrosis virus  0.01654   
1     vrl        0     1474                         Bohle iridovirus  0.02714   
2     vrl        0     4862             Sweet potato leaf curl virus  0.01974   
3     vrl        0     1915             Northern cereal mosaic virus  0.01775   
4     vrl        0    22831           Soil-borne cereal mosaic virus  0.02816   

       UUC      UUA      UUG      CUU      CUC  ...      AGA      AGG  \
0  0.01203  0.00050  0.00351  0.01203  0.03208  ...  0.01303  0.03559   
1  0.01357  0.00068  0.00678  0.00407  0.02849  ...  0.01696  0.03596   
2  0.02180  0.01357  0.01543  0.00782  0.01111  ...  0.01974  0.02489   
3  0.02245  0.01619  0.00992  0.01567  0.01358  ...  0.01410  0.01671   
4  0.01371  0.00767  0.03679  0.01380  0.00548  ...  0.01494  0.01734   

       GAU      GAC      GAA      GAG      UAA      UAG      UGA  Cluster_  
0  0.01003  0.04612  0.01203  0.04361  0.00251  0.00050  0.00000         9  
1  0.01221  0.04545  0.01560  0.04410  0.00271  0.00068  0.00000         9  
2  0.03126  0.02036  0.02242  0.02468  0.00391  0.00000  0.00144         0  
3  0.03760  0.01932  0.03029  0.03446  0.00261  0.00157  0.00000         0  
4  0.04148  0.02483  0.03359  0.03679  0.00000  0.00044  0.00131         0  

[5 rows x 69 columns]

In [30]:
rna.tail()

Kingdom  DNAtype   Ncodons                            SpeciesName  \
13021     pri        0      1097                  Pongo pygmaeus abelii   
13022     pri        1      2067    mitochondrion Pongo pygmaeus abelii   
13023     pri        1      1686  mitochondrion Pongo pygmaeus pygmaeus   
13024     pri        0  40662582                           Homo sapiens   
13025     pri        1   8998998             mitochondrion Homo sapiens   

           UUU      UUC      UUA      UUG      CUU      CUC  ...      AGA  \
13021  0.02552  0.03555  0.00547  0.01367  0.01276  0.02097  ...  0.01367   
13022  0.01258  0.03193  0.01984  0.00629  0.01451  0.05322  ...  0.00000   
13023  0.01423  0.03321  0.01661  0.00356  0.01127  0.05042  ...  0.00000   
13024  0.01757  0.02028  0.00767  0.01293  0.01319  0.01959  ...  0.01217   
13025  0.01778  0.03724  0.01732  0.00600  0.01689  0.03854  ...  0.00041   

           AGG      GAU      GAC      GAA      GAG      UAA      UAG      UGA  \
13021  0.01094  0.01367  0.02279  0.02005  0.04102  0.00091  0.00091  0.00638   
13022  0.00048  0.00194  0.01306  0.01838  0.00677  0.00242  0.00097  0.01887   
13023  0.00000  0.00178  0.01661  0.02788  0.00297  0.00356  0.00119  0.02017   
13024  0.01196  0.02178  0.02510  0.02896  0.03959  0.00099  0.00079  0.00156   
13025  0.00041  0.00451  0.01402  0.01651  0.00783  0.00156  0.00114  0.02161   

       Cluster_  
13021         0  
13022         2  
13023         2  
13024         5  
13025         2  

[5 rows x 69 columns]

In [31]:
'''
# Apply hierachical clustering
import scipy.cluster.hierarchy
Z = scipy.cluster.hierarchy.linkage(dist_matrix, 'complete')
scipy.cluster.hierarchy.dendogram(Z)
plt.show()
'''

"\n# Apply hierachical clustering\nimport scipy.cluster.hierarchy\nZ = scipy.cluster.hierarchy.linkage(dist_matrix, 'complete')\nscipy.cluster.hierarchy.dendogram(Z)\nplt.show()\n"

In [32]:
rna.head()

Kingdom  DNAtype  Ncodons                              SpeciesName      UUU  \
0     vrl        0     1995  Epizootic haematopoietic necrosis virus  0.01654   
1     vrl        0     1474                         Bohle iridovirus  0.02714   
2     vrl        0     4862             Sweet potato leaf curl virus  0.01974   
3     vrl        0     1915             Northern cereal mosaic virus  0.01775   
4     vrl        0    22831           Soil-borne cereal mosaic virus  0.02816   

       UUC      UUA      UUG      CUU      CUC  ...      AGA      AGG  \
0  0.01203  0.00050  0.00351  0.01203  0.03208  ...  0.01303  0.03559   
1  0.01357  0.00068  0.00678  0.00407  0.02849  ...  0.01696  0.03596   
2  0.02180  0.01357  0.01543  0.00782  0.01111  ...  0.01974  0.02489   
3  0.02245  0.01619  0.00992  0.01567  0.01358  ...  0.01410  0.01671   
4  0.01371  0.00767  0.03679  0.01380  0.00548  ...  0.01494  0.01734   

       GAU      GAC      GAA      GAG      UAA      UAG      UGA  Cluster_  
0  0.01003  0.04612  0.01203  0.04361  0.00251  0.00050  0.00000         9  
1  0.01221  0.04545  0.01560  0.04410  0.00271  0.00068  0.00000         9  
2  0.03126  0.02036  0.02242  0.02468  0.00391  0.00000  0.00144         0  
3  0.03760  0.01932  0.03029  0.03446  0.00261  0.00157  0.00000         0  
4  0.04148  0.02483  0.03359  0.03679  0.00000  0.00044  0.00131         0  

[5 rows x 69 columns]

In [34]:
# Assuming 'labels' is a list of labels for each data point
labels = rna['Kingdom'].tolist()  # Or any other relevant column for labels

# Apply hierarchical clustering
import scipy.cluster.hierarchy
Z = scipy.cluster.hierarchy.linkage(dist_matrix, 'average')
dendrogram = scipy.hierarchy.dendrogram(Z, labels=labels)
plt.show()

<ipython-input-34-ba1afd4f384d>:6: ClusterWarning: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  Z = scipy.cluster.hierarchy.linkage(dist_matrix, 'average')


NameError: name 'sch' is not defined

In [ ]:
#Appyling DBSCAN





In [35]:
#Applying k-means clustering
from sklearn.cluster import KMeans
kmeans = KMeans(init = 'k-means++', n_clusters=11, n_init=10)
kmeans.fit(rna)
kmeans.labels_

#A graph to show the clusters
plt.scatter(kmeans.labels_, kmeans.labels_)
plt.show()


ValueError: could not convert string to float: 'vrl'